services:
  db:
    image: db-postgresql:latest
    container_name: skynet-postgres
    build:
      context: .
      dockerfile: Dockerfile
    environment: 
      POSTGRES_NAME: postgres
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      TZ: America/Argentina/Buenos_Aires
    ports:
      - 5432:5432
    volumes:
      - .data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
networks:
  default:
    name: skynet
