services:
  tp-cache-interna:
    image: tp3-redis:latest
    container_name: tp3-redis
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - JAVA_OPTS=-agentlib:jdwp=transport=dt_socket,address=0.0.0.0:5000,server=y,suspend=n
    ports:
      - 8080:8080
      - 5000:5000
networks:
  default:
    name: skynet
